
server:
  port: 8080

spring:
  application:
    name: ex-logic

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-1-server.com:9001/eureka/, http://eureka-2-server.com:9002/eureka/, http://eureka-3-server.com:9003/eureka/}
